### PR TITLE
TTL binary to decimal event

### PR DESCRIPTION
**Pull request by m4loman**
Hi,

this would be super helpful to include. Includes a conversion from the TTL lines to a decimal (0-255) that would then need to be saved as either a message or a new event type.

Thanks Jan

### CODE REVIEW

**Comment by aacuevas** [comment]
This functionality already exists in the GUI: each TTL event contains the full word detected by the acquisition hardware. It can be accessed in any method that deals with the event buffer by something like:
uint8* dataptr = )event.getRawData();
uint64 ttlWord = *((uint64*)(dataptr+6));

**Comment by m4loman** [comment]
That is great Aaron,
can we save this as a new type of event in the main branch without adding a new node then? If yes, what would be consistent to use ?

Thus, if any TTL line changes state during a sample update all TTL line event states and then output one decimal converted number.

All the best

Jan

**Comment by aacuevas** [comment]
I wouldn't add another type of event for this, as the data is already present in the TTL events. Any processor can use it with the code I posted before.

This full word is still not saved to file, though, but it is comething I'm going to add soon.

**Comment by m4loman** [comment]
Thanks Aaron, let me know when you have it in the save files. Lets just go that route then.

**Pull request closed without merging**
