### PR TITLE
Event Broadcaster sink

### PR DESCRIPTION
**Pull request by cstawarz**
These changes add a new sink type, "Event Broadcaster", that makes Open Ephys events accessible to external processes via a ZeroMQ PUB socket.  The file `Resources/Python/event_listener.py` implements a subscriber to the published events (for testing and demonstration).

Each event is transmitted as a ZeroMQ multi-part message with three parts:

1. Event type (single byte)
2. Event time in seconds (little-endian `double`)
3. "Raw" OE event, minus the event type

I opted to send the raw event data because (1) I wasn't certain how many fields of certain event types (e.g. spikes) would be useful to clients and therefore didn't want to omit any, and (2) I didn't have a preference for any particular serialization format, and using the raw event data was perfectly acceptable for my purposes.  As a future enhancement, I can imagine adding a drop-down menu in the Event Broadcaster editor that lets the user choose from a selection of serialization formats (e.g. [JSON](http://json.org), [BSON](http://bsonspec.org), [msgpack](http://msgpack.org)) in addition to the current "raw" format.

These changes also add a new event type, `TTL_WORD`, whose payload is a little-endian `uint64` where each bit represents the state of a TTL line.  Such an event is generated for every sample in which one or more TTL line states has changed.  I added this because I want to send multi-bit sync words from an external application and echo them back via the event broadcaster, and reconstructing the word from individual `TTL` events proved awkward.  I'm not 100% sure this is the right solution for my problem, so I'm open to suggestions for better ways to do it.

### CODE REVIEW

**Comment by aacuevas** [comment]
Hi,

Thanks for the module, it's a greatly appreciated contribution.
What we're a bit unsure of is the new event type. We recently did a cleanup on those, and adding new ones causes no short amount of trouble down the chain. Why's awkward reconstructing the words from the edge events? We chose sending separate edge events because that's what most processors needed and we'd like to minimice data redundancy.

**Comment by cstawarz** [comment]
> Why's awkward reconstructing the words from the edge events?

The problem is that it's tricky to know when a complete new word has been received.

Consider the case of a two-bit word, where the least-significant bit is sent to TTL input channel 1, and the most-significant bit goes to channel 2.  Assume that the external application is just cycling through all integers that can be represented by two bits, thereby sending the sequence 0, 1, 2, 3, 0, 1, 2, 3... repeatedly.

When the first value (0) is received, Open Ephys generates two TTL events, one each for channels 1 and 2.  Then, when the second value (1) comes in, only one TTL event is generated, as only channel 1 changes state.  If an external listener (connected to the OE event stream via an event broadcaster) is trying to keep track of the word values that OE is receiving, how is the listener supposed to know that the single TTL event represents a complete word value of 1, as opposed to just the first half of 3?

You might try just waiting until the *next* time channel 1 changes to confirm the previous change.  However, in addition to the obvious disadvantage of having to wait a potentially arbitrary amount of time for confirmation of the word value, this technique would only work for value sequences that strictly increased (or decreased) by one at every step.  In other words, it wouldn't work if the sequence were 0, 2, 1, 3, as in that case channel 1 would change only every other word.

The only solution (that I can think of, anyway) that really works is to generate your word sequence so that the bit corresponding to the highest-numbered OE channel changes every time the word value changes.  (For example, for two-bit words, 0, 2, 1, 3 would work, as channel 2 would change every time.)  That way,   every time you saw a TTL event for the high channel, you would know that the complete word had been received.  This works, but as I said initially, it's awkward, and I suspect it would be confusing and error-prone for end users.

As an alternative to a global `TTL_WORD` event type, I believe it would be possible for the event broadcaster instance to reconstruct the words itself, and then generate its own "whole word"-type event to send to clients.  However, that would mean creating its own event-type code, which could potentially conflict with future, standard OE event types.

Another option would be to give standard TTL events the same payload as TTL_WORD, i.e a 64-bit integer representing the states of *all* TTL lines.  It seems like that would entail a pretty minor increase in the amount of raw data going down the pipe, but maybe it would also cause problems farther down the chain.

**Comment by aacuevas** [comment]
Sorry for taking so long, we had to discuss this a bit.

I've implemented your last suggestion, which is a very good compromise. A ttl event now holds a 64bit payload with the full word, so you can use that. If you can please reissue the pull request without the event type related changes (GenericProcessor and SourceNode changes) I'll merge it.

**Comment by cstawarz** [comment]
OK, I've resubmitted this as pull request #314.  Thanks!

**Comment by m4loman** [comment]
Hey guys I am slightly confused by this discussion even even more by the commit :)

Does this mean the current master build has the functionality of strobe triggered bit words built in and if yes how does it work and how do I use it?

Plexon for example has the simple 1 TTL line strobe 8 TTL lines bit 0-256. In the files itself you only see the 0-256 and everything is taken care of.

Would you mind elaborating a little on the changes that have been made?

Kind regards

Jan

**Comment by cstawarz** [comment]
> Does this mean the current master build has the functionality of strobe triggered bit words built in

No.  The only TTL-related commit to emerge from this pull request is f84d120, and those changes only matter if you want to process raw `TTL` events (either in an OE processor or in an external Event Broadcaster client).  The user-facing aspects of TTL handling have not changed at all.

**Pull request closed without merging**
